version: "3.5"

services:
   php_fpm:
	build: .
	container_name: bonsae_php_fpm
	working_dir: /usr/share/nginx/bonsae		networks:
			- bonsae
		volumes:
			- ./:/usr/share/nginx/bonsae

	nginx:
		image: nginx:1.15
		container_name: bonsae_nginx
		working_dir: /usr/share/nginx/bonsae
		networks:
			- bonsae
		ports:
			- "8000:80"
		volumes:
			- ./:/usr/share/nginx/bonsae
			- ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

	mysql:
		image: mysql:5.7
		container_name: bonsae_mysql
		networks:
			- bonsae
		enviroment:
			- MYSQL_DATABASE=bonsae
			- MYSQL_ROOT_PASSWORD=password
			- MYSQL_USER=root
			- MYSQL_PASSWORD=password

networks:
	bonsae:
		driver: bridge
